FROM python:3.4-slim

ENV CLUSTERRUNNER_VERSION=0.5.474

RUN apt-get update -y \
        && apt-get install -y gcc git \
        && apt-get clean

RUN git clone -b $CLUSTERRUNNER_VERSION \
	https://github.com/box/ClusterRunner.git /src

RUN pip install --upgrade -r /src/requirements.txt

EXPOSE 43000 43001

ENTRYPOINT ["/src/main.py"]
